namespace Maho.Resolution;

internal abstract class Symbol
{
    public SymbolID ID { get; }
    public SymbolPart Name { get; }
    public SymbolKind Kind { get; init; }
    public Scope EnclosingScope { get; }

    /// <summary> Gets the hygiene context of this symbol. </summary>
    public HygieneId Hygiene => Name.Hygiene;

    /// <summary> Gets whether this symbol was generated by macro expansion. </summary>
    public bool IsMacroGenerated => Name.Hygiene.IsMacroGenerated;

    public Symbol(SymbolID id, SymbolPart name, Scope enclosingScope)
    {
        ID = id;
        Name = name;
        EnclosingScope = enclosingScope;
    }
}